language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.3'
  - '7.4'

matrix:
  include:
    - php: 7.3
      env: COMPOSER_VERSION=1.10
    - php: 7.3
      env: COMPOSER_VERSION=2.0.3
    - php: 7.4
      env: COMPOSER_VERSION=1.10
    - php: 7.4
      env: COMPOSER_VERSION=2.0.3

before_script:
  - composer self-update ${COMPOSER_VERSION}
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
